title: Discord Bot Documentation
description: Documentation for the Discord bot
baseurl: "/documentation"
url: ""
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

sass:
  style: compressed
  sass_dir: docs/_sass

# Navigation
nav_pages:
  - title: Home
    url: /
  - title: Commands
    url: /documentation/pages/commands/
  - title: Setup
    url: /documentation/pages/setup/
  - title: Configuration
    url: /documentation/pages/configuration/
  - title: Development
    url: /documentation/pages/development/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor