title: Discord Bot Documentation
description: Documentation for the Discord bot
baseurl: "https://jacob-walton.github.io"
url: "/discord-bot-documentation/documentation"
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
nav_pages:
  - title: Home
    url: /documentation/
  - title: Commands
    url: /documentation/pages/commands
  - title: Setup
    url: /documentation/pages/setup
  - title: Configuration
    url: /documentation/pages/configuration
  - title: Development
    url: /documentation/pages/development

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor